(#1501796) backport of unit_watch_pid() with new 'exclusive' flag (PR #12033)
systemd-rhel/rhel-7 pull request #37
Opened 2019-08-26 07:42 UTC by dtardon

Signed-off-by: Renaud Métrich <rmetrich@redhat.com>

Resolves: #1501796

2019-08-27 14:24 UTC, msekletar commented on src/core/unit.c
> +                        log_unit_debug(u->id, "Warning: cannot watch "PID_FMT", PID is already watched twice.", pid);
I think that is a good idea. In an ideal world, this situation shouldn't really happen very often anyway.

2019-08-28 07:49 UTC, rmetrich commented on src/core/unit.c
> +                        log_unit_debug(u->id, "Warning: cannot watch "PID_FMT", PID is already watched twice.", pid);
@dtardon Hello, as discussed yesterday with @msekletar please change line 2001 from **log_unit_debug** to **log_unit_warning** and remove `Warning:` prefix and we are good to merge.

2019-08-28 08:02 UTC, dtardon commented on src/core/unit.c
> +                        log_unit_debug(u->id, "Warning: cannot watch "PID_FMT", PID is already watched twice.", pid);
Done.

2019-09-04 12:18 UTC, msekletar requested changes
David, can you please also drop the Signed-off line and provide a reference to upstream commit?

2019-09-04 12:23 UTC, msekletar commented
Actually we should properly cherry-pick the upstream commit also with the commit message.

2019-09-11 08:23 UTC, dtardon commented
Updated.

2019-09-24 11:43 UTC, msekletar approved these changes
LGTM

2019-09-25 15:20 UTC, merged