(#1525999) Make sure we don't loose stream FDs on journald restart
systemd-rhel/rhel-7 pull request #49
Opened 2019-09-24 11:11 UTC by msekletar

2019-09-26 08:18 UTC, jsynacek commented
All CI checks are unrelated.

2019-09-26 09:33 UTC, jsynacek requested changes

2019-09-26 09:33 UTC, jsynacek commented on src/core/service.c
> +        log_unit_debug(UNIT(s), "Releasing all stored fds");
This should say UNIT(s)->id. I'm not sure if other patches fix it.

2019-09-26 11:34 UTC, dtardon reviewed
LGTM with the exception of the mistake @jsynacek has found.

2019-09-26 17:10 UTC, msekletar commented
Fixed. @jsynacek @dtardon please have one more look and give yay or nay. Thanks!

2019-09-27 07:11 UTC, dtardon approved these changes
LGTM now.

2019-09-27 08:40 UTC, jsynacek approved these changes
LGTM.

2019-10-03 07:57 UTC, merged