(#1786126) fgets line split 7.5.z
systemd-rhel/rhel-7 pull request #67
Opened 2020-01-15 11:28 UTC by jsynacek

2020-01-16 08:22 UTC, jsynacek commented
Travis CI failure is unrelated to the patch.

2020-01-20 15:33 UTC, dtardon requested changes

2020-01-20 15:33 UTC, dtardon commented on src/core/manager.c
> +                        return log_error_errno(r, "Failed to read serialization line: %m");
Eh. We screwed this up in the original backport. If this `return` ever happens, `m->n_reloading` will remain >0, with unclear consequences (but I doubt they will be positive). The `return` needs to be changed to `goto finish`.

2020-01-20 15:33 UTC, dtardon commented on src/core/manager.c
> +                        return log_error_errno(r, "Failed to read serialization line: %m");
Ditto.

2020-01-21 11:13 UTC, jsynacek commented
v2.

2020-01-21 11:20 UTC, dtardon approved these changes
LGTM

2020-01-21 11:37 UTC, merged